export GIT_EDITOR=emacsclient
export BUNDLER_EDITOR=emacsclient

alias be='bundle exec'
alias bec='bundle exec cucumber'
alias becw='bundle exec cucumber --tags @wip'
alias ber='bundle exec rake'
alias ec='emacsclient'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff --color --word-diff'
alias gl='git log --decorate'
alias gpl='git pull'
alias gps='git push'
alias gs='git status'
alias gsp='git stash pop'
alias gss='git stash save'
alias sv="read -rs __VARNAME < /dev/tty; read -rs \$__VARNAME < /dev/tty"

export GOPATH="$HOME/code/go"
export PATH="$HOME/.rbenv/bin:$HOME/.roswell/bin:$HOME/.local/bin/:$PATH:$GOPATH/bin:"
eval "$(rbenv init -)"

export LC_ALL="en_AU.UTF-8"

# some .profile overrides
BLOCKSIZE=K;	export BLOCKSIZE
EDITOR=emacs; export EDITOR
PAGER=less;  	export PAGER

# use fzf for fuzzy search / completion
source /usr/local/share/examples/fzf/shell/completion.zsh
source /usr/local/share/examples/fzf/shell/key-bindings.zsh

echo
fortune | cowsay -W 78

# use nvm for Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
